# 
# Synthesis run script generated by Vivado
# 

set TIME_start [clock seconds] 
proc create_report { reportName command } {
  set status "."
  append status $reportName ".fail"
  if { [file exists $status] } {
    eval file delete [glob $status]
  }
  send_msg_id runtcl-4 info "Executing : $command"
  set retval [eval catch { $command } msg]
  if { $retval != 0 } {
    set fp [open $status w]
    close $fp
    send_msg_id runtcl-5 warning "$msg"
  }
}
set_param chipscope.maxJobs 4
set_param synth.incrementalSynthesisCache C:/Users/asus/AppData/Roaming/Xilinx/Vivado/.Xil/Vivado-10360-LAPTOP-A50L20VJ/incrSyn
set_param xicom.use_bs_reader 1
set_msg_config -id {Synth 8-256} -limit 10000
set_msg_config -id {Synth 8-638} -limit 10000
create_project -in_memory -part xc7a100tcsg324-3

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_msg_config -source 4 -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property webtalk.parent_dir F:/vivado_project/project_vga/project_vga.cache/wt [current_project]
set_property parent.project_path F:/vivado_project/project_vga/project_vga.xpr [current_project]
set_property XPM_LIBRARIES {XPM_CDC XPM_MEMORY} [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property ip_output_repo f:/vivado_project/project_vga/project_vga.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
add_files f:/vivado_project/project_vga/project_vga.srcs/sources_1/ip/picture_12bit.coe
read_mem F:/vivado_project/project_vga/project_vga.srcs/sources_1/new/background_4bit.mem
read_verilog -library xil_defaultlib {
  F:/vivado_project/project_vga/project_vga.srcs/sources_1/new/anim_gen.v
  F:/vivado_project/project_vga/project_vga.srcs/sources_1/new/bram_background.v
  F:/vivado_project/project_vga/project_vga.srcs/sources_1/new/button_pulse.v
  F:/vivado_project/project_vga/project_vga.srcs/sources_1/new/clock_core.v
  F:/vivado_project/project_vga/project_vga.srcs/sources_1/new/seg_display.v
  F:/vivado_project/project_vga/project_vga.srcs/sources_1/new/vga_timing.v
  F:/vivado_project/project_vga/project_vga.srcs/sources_1/new/vga_out.v
}
read_ip -quiet f:/vivado_project/project_vga/project_vga.srcs/sources_1/ip/blk_mem_gen_0/blk_mem_gen_0.xci
set_property used_in_implementation false [get_files -all f:/vivado_project/project_vga/project_vga.srcs/sources_1/ip/blk_mem_gen_0/blk_mem_gen_0_ooc.xdc]

read_ip -quiet F:/vivado_project/project_vga/project_vga.srcs/sources_1/ip/clk_wiz_0/clk_wiz_0.xci
set_property used_in_implementation false [get_files -all f:/vivado_project/project_vga/project_vga.srcs/sources_1/ip/clk_wiz_0/clk_wiz_0_board.xdc]
set_property used_in_implementation false [get_files -all f:/vivado_project/project_vga/project_vga.srcs/sources_1/ip/clk_wiz_0/clk_wiz_0.xdc]
set_property used_in_implementation false [get_files -all f:/vivado_project/project_vga/project_vga.srcs/sources_1/ip/clk_wiz_0/clk_wiz_0_ooc.xdc]

# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
read_xdc F:/vivado_project/project_vga/project_vga.srcs/constrs_1/new/VGA.xdc
set_property used_in_implementation false [get_files F:/vivado_project/project_vga/project_vga.srcs/constrs_1/new/VGA.xdc]

read_xdc dont_touch.xdc
set_property used_in_implementation false [get_files dont_touch.xdc]
set_param ips.enableIPCacheLiteLoad 1
close [open __synthesis_is_running__ w]

synth_design -top vga_out -part xc7a100tcsg324-3


# disable binary constraint mode for synth run checkpoints
set_param constraints.enableBinaryConstraints false
write_checkpoint -force -noxdef vga_out.dcp
create_report "synth_1_synth_report_utilization_0" "report_utilization -file vga_out_utilization_synth.rpt -pb vga_out_utilization_synth.pb"
file delete __synthesis_is_running__
close [open __synthesis_is_complete__ w]
